= Starship Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Fedora: https://fedoraproject.org/[Fedora]
:fish: https://fishshell.com/[fish]
:just: https://github.com/casey/just[just]
:Nerd-Fonts: https://www.nerdfonts.com/[Nerd Fonts]
:Noto: https://notofonts.github.io/[Noto]
:Nushell: https://nushell.sh/[Nushell]
:Starship: https://starship.rs/[Starship]

My configuration for {Starship}, the minimal, blazing-fast, and infinitely customizable prompt for any shell!

== Usage

This repository contains the configuration files for {Starship}, which I use for both {fish} and {Nushell}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.
{Nerd-Fonts} are required for this configuration.
I use the patched {Noto} fonts.
Noto Sans is the default font used in {Fedora} Linux.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone git@codeberg.org:jwillikers/starship-config.git
----

. Change to the project's directory.
+
[,sh]
----
cd starship-config
----

. Run `just` to install Nerd Fonts, Starship, and the config file.
+
[,sh]
----
just
----

. On Fedora Atomic systems, reboot for the changes to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Follow the install instructions in the https://github.com/jwillikers/fish-config[fish config repository] and https://github.com/jwillikers/nushell-config[Nushell config repository] to enable Starship.
For other shells, refer to the https://starship.rs/guide/#%F0%9F%9A%80-installation[Starship Installation instructions].

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
